name: 💡 Feature request
description: Suggest an idea or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
      description: The use case or frustration behind the request.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: What would you like to happen?

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
